version: '3'
services:
  spoilersbot:
    build: .
    volumes:
      - './app/db:/usr/src/app/db'
      - './app/log:/usr/src/app/log'
    logging:
      driver: json-file
      options:
        max-size: "10m"
    command: python startbot.py

